
version: '3'

services:
  api:
    image: ghcr.io/nils-witt/s-plan_api:latest
    restart: always
    environment:
      # API Self
      API_URL: "https://api.splan.nils-witt.de"

      # Developer Settings
      APIDOC: "false"

      #PWA
      PWA_URL: "https://pwa.splan.example.de"

      #Display
      DISPLAY_URL: "https://display.splan.example.de"
      #Notifications

      ##Telegram
      TELEGRAM: "false"
      TELEGRAM_KEY: ""
      TELEGRAM_VALIDATION_URL: "https://pwa.splan.example.de/pages/linkTelegram.html"

      # FCM
      FCM: "false"
      FCM_URL: "https://url_server.firebaseio.com"
      FCM_CREDENTIALS: "/home/node/app/keys/fcm_key.json"

      # WebPush
      WEBPUSH: "false"
      VAPID_PUBLIC: "VAPID_PUBLIC"
      VAPID_PRIVATE: "VAPID_PRIVATE"
      VAPID_SUBJECT: "mailto:admin@example.de"

      # LDAP
      LDAP: "true"

      LDAP_HOST: "ldap://127.0.0.1:389"
      LDAP_ROOT: "DC=domain,DC=local"
      LDAP_DOMAIN: "domain"

      LDAP_STUDENTSGROUP: "CN=Students,DC=domain,DC=local"
      LDAP_TEACHERGROUP: "CN=Teachers,DC=domain,DC=local"

      LDAP_USER: "user"
      LDAP_PASS: "pass"

      LDAP_TLS: "false"
      LDAP_CA_PATH: "/home/node/app/keys/ldap-ca.pem"

      # MySQL
      SQL_PORT: "3306"
      SQL_HOST: "mysql"
      SQL_USER: "splan"
      SQL_PASS: "splan"
      SQL_DB: "splan"

      # Moodle
      MOODLE: "false"
      MOODLE_HOST: "moodle.example.de"
      MOODLE_PATH: ""
      MOODLE_KEY: "KEY"

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "splan"
      MYSQL_DATABASE: "splan"
      MYSQL_USER: "splan"
      MYSQL_PASSWORD: "splan"
    volumes:
      - ./database:/var/lib/mysql
      - ./ressources/splan-database.sql:/docker-entrypoint-initdb.d/splan-database.sql
    ports:
      - "3306:3306"
